name: My workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t rmv-reminder .
      - name: Run Docker container
        env:
          ACTION_GOOGLE_API_KEY: ${{ secrets.ACTION_GOOGLE_API_KEY }}
          ACTION_NOTIFICATION_SENDER_EMAIL_PASSWORD: ${{ secrets.ACTION_NOTIFICATION_SENDER_EMAIL_PASSWORD }}
          ACTION_SMS_TOKEN_KEY_VALUE: ${{ secrets.ACTION_SMS_TOKEN_KEY_VALUE }}
          NOTIFICATION_SENDER_EMAIL: ${{ secrets.NOTIFICATION_SENDER_EMAIL }}
        run: docker run -e GOOGLE_API_KEY=${{ secrets.ACTION_GOOGLE_API_KEY }} -e ACTION_NOTIFICATION_SENDER_EMAIL_PASSWORD -e ACTION_SMS_TOKEN_KEY_VALUE -e NOTIFICATION_SENDER_EMAIL rmv-reminder
