name: My workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t rmv-reminder .
      - name: Run Docker container
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NOTIFICATION_SENDER_EMAIL_PASSWORD: ${{ secrets.NOTIFICATION_SENDER_EMAIL_PASSWORD }}
          SMS_TOKEN: ${{ secrets.SMS_TOKEN }}
          NOTIFICATION_SENDER_EMAIL: ${{ secrets.NOTIFICATION_SENDER_EMAIL }}
          TEST: ${{ secrets.TEST }}
        run: docker run -e GOOGLE_API_KEY -e NOTIFICATION_SENDER_EMAIL_PASSWORD -e NOTIFICATION_SENDER_EMAIL -e SMS_TOKEN -e TEST rmv-reminder
